#!/bin/sh

ROOT="`pwd`/build"
mkdir -p $ROOT

after_install_script="$ROOT/after_install.sh"
RPMROOT="$ROOT/rpmbuild"
DEBROOT="$ROOT/debbuild"

cat > $after_install_script << EOF
systemctl daemon-reload
EOF

VERSION=$(cat VERSION)

BIN="$RPMROOT/usr/bin"
CONF="$RPMROOT/etc/eru"
SERVICE="$RPMROOT/usr/lib/systemd/system"

mkdir -p $BIN
mkdir -p $SERVICE
mkdir -p $CONF

cp eru-minions $BIN/eru-minions
cp eru-minions.service $SERVICE
cp minions.conf $CONF

echo $VERSION rpm build begin

fpm -f -s dir -t rpm -n eru-minions --epoch 0 -v $VERSION --iteration 1.el7 -C $RPMROOT -p $PWD --verbose --category 'Development/App' --description 'docker eru minions' --after-install $after_install_script --url 'https://github.com/projecteru2/minions' --license 'MIT'  --no-rpm-sign usr etc

BIN="$DEBROOT/usr/bin"
CONF="$DEBROOT/etc/eru"
SERVICE="$DEBROOT/lib/systemd/system"

mkdir -p $BIN
mkdir -p $CONF
mkdir -p $SERVICE

cp eru-minions $BIN
cp minions.conf $CONF
cp eru-minions.service $SERVICE

echo $VERSION deb build begin

fpm -f -s dir -t deb -n eru-minions -v $VERSION --iteration 1.noarch -C $DEBROOT -p $PWD --verbose --category 'Development/App' --description 'docker eru minions' --url 'https://github.com/projecteru2/minions' --license 'MIT' --after-install $after_install_script --deb-no-default-config-files usr etc lib

rm -rf $ROOT
