#!/bin/bash

set -e
ROOT="`pwd`/build"
BIN="$ROOT/usr/bin"
CONF="$ROOT/etc/eru"
SERVICE="$ROOT/usr/lib/systemd/system"
after_install_script="$ROOT/after_install.sh"

mkdir -p $BIN
mkdir -p $SERVICE
mkdir -p $CONF

cat > $after_install_script << EOF
systemctl daemon-reload
EOF

mv eru-minions $BIN/eru-minions
mv eru-minions.service $SERVICE
mv minions.conf $CONF

VERSION=$(cat VERSION)
echo $VERSION rpm build begin

fpm -f -s dir -t rpm -n eru-minions --epoch 0 -v $VERSION --iteration 1.el7 -C $ROOT -p $PWD --after-install $after_install_script --verbose --category 'Development/App' --description 'docker eru minions' --url 'https://github.com/projecteru2/minions' --license 'MIT'  --no-rpm-sign usr etc

rm -rf $ROOT
