appname: "eru"
entrypoints:
  minions:
    cmd: "/usr/bin/eru-minions"
    restart: "always"
    privileged: true
volumes:
  - "/var/run/docker/plugins/:/var/run/docker/plugins"

stages:
  - build
  - pack
builds:
  build:
    base: "golang:alpine"
    repo: "git@github.com:projecteru2/minions.git"
    version: "HEAD"
    dir: /go/src/github.com/projecteru2/minions
    commands:
      - apk add --no-cache git ca-certificates curl make alpine-sdk linux-headers
      - make build
      - ./eru-minions --version
    cache:
      /go/src/github.com/projecteru2/minions/eru-minions: /usr/bin/eru-minions
  pack:
    base: alpine
    labels:
      ERU: 1
      version: latest
    commands:
      - mkdir -p /etc/eru/
